query GET_PERSON {
  id
  name
  age
  married
}

query GET_DOCUMENTS {
  # Se você estiver buscando um Array a query dever ser igual a isso, para afetar os objetos dentro do array.
  documents {
    RG
  }
}

query GET_USER_BY_ID {
  user(id: "602") {
    id
    firstName
    lastName
    userName
    indexRef
    createdAt
  }
}
