query GET_PERSON {
  id
  name
  age
  married
}

query GET_DOCUMENTS {
  # Se você estiver buscando um Array a query dever ser igual a isso, para afetar os objetos dentro do array.
  documents {
    RG
  }
}

query GET_USER_BY_ID {
  user(id: "602") {
    id
    firstName
    lastName
    userName
    indexRef
    createdAt
  }
}

query GET_POST_BY_ID($postId: ID!) {
  post(id: $postId) {
    title
  }
}

query GET_POST_ALIAS {
  posts860: post(id: "860") {
    id
    titlePost: title
  }

  post940: post(id: "940") {
    postId: id
    id
    title
  }
}


fragment post on Posts {
  id
  title
}

query GET_POST_WITH_FRAGMENT {
  posts860: post(id: "860") {
    ...post
  }

  post940: post(id: "940") {
    ...post
  }
}
